---
groups:
- name: cf-deploy-app
  jobs:
  - deploy-application
  - tag

jobs:
- name: deploy-application
  serial: true
  public: true
  plan:
  - get: app-source
    trigger: true
  - put: resource-deploy-app
    params:
      manifest: app-source/manifest.yml
    on_failure:
      put: failure-alert
      params:
        channel:  logsearch
        username: concourse-ci
        icon_url: https://i.imgur.com/eioobYI.png
        text:     {{slack-text}}
- name: tag
  public: true
  serial: true
  plan:
  - get: app-source
    passed: [deploy-application]
  - put: version
    params: {bump: minor}
  - put: app-source
    params:
      only_tag: true
      repository: app-source
      tag: version/number

resources:
- name: app-source
  type: git
  source:
    uri: git@github.com:Infra-Red/app-pipeline-demo.git
    branch: master
    private_key: {{github-private-key}}
- name: failure-alert
  type: slack-notification
  source:
    url: {{slack-url}}
- name: resource-deploy-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-user}}
    password: {{cf-pass}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false
- name: version
  type: semver-gwenn
  source:
    driver: git
    uri: git@github.com:Infra-Red/app-pipeline-demo.git
    branch: version
    file: version
    private_key: {{github-private-key}}
    git_user: Infra-Red

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
